/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/Pixel6.glb 
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/google-pixel-6-pro-b9b58ca40c254f8dafd8370869af74fb
Title: Google Pixel 6 Pro
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GooglePixelModel(props) {
  const { nodes, materials } = useGLTF('./models/Pixel6.glb')
  return (
    <group {...props} dispose={null} position={[0, 0.7, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.045}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.14}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frame_Frame_0.geometry} material={materials.Frame} />
            <mesh geometry={nodes.Frame_CamModuleBlack_0.geometry} material={materials.CamModuleBlack} />
            <mesh geometry={nodes.Frame_CamModule_0.geometry} material={materials.CamModule} />
            <mesh geometry={nodes.Frame_Mic_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Frame_Antennas_0.geometry} material={materials.Antennas} />
            <mesh geometry={nodes.Frame_CamGlass_0.geometry} material={materials.CamGlass} />
            <mesh geometry={nodes.Screen_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes['BackBody_Back(top)_0'].geometry} material={materials.Backtop} />
            <mesh geometry={nodes['BackBody_Back(Bottom_0'].geometry} material={materials.BackBottom} />
            <mesh geometry={nodes.CircleCam_CamGray_0.geometry} material={materials.CamGray} />
            <mesh geometry={nodes.Sensor2_Sensor_0.geometry} material={materials.Sensor} />
            <mesh geometry={nodes.RecCam_CamGray_0.geometry} material={materials.CamGray} />
            <mesh geometry={nodes.RecCam_CamGlass_0.geometry} material={materials.CamGlass} />
            <mesh geometry={nodes.Sensor_Sensor001_0.geometry} material={materials['Sensor.001']} />
            <mesh geometry={nodes.Flash_Flash_0.geometry} material={materials.Flash} />
            <mesh geometry={nodes.Mic_Mic2_0.geometry} material={materials.Mic2} />
            <mesh geometry={nodes.Mic_Mic_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Frontcam_CamGray_0.geometry} material={materials.CamGray} />
            <mesh geometry={nodes.Frontcam_CamGlass_0.geometry} material={materials.CamGlass} />
            <mesh geometry={nodes.Bezel_Bezel_0.geometry} material={materials.Bezel} />
            <mesh geometry={nodes.Bezel_Mic_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Buttons_Frame_0.geometry} material={materials.Frame} />
            <mesh geometry={nodes.Lens3_Lens_0.geometry} material={materials.Lens} />
            <mesh geometry={nodes.CircleCam2_CamGray_0.geometry} material={materials.CamGray} />
            <mesh geometry={nodes.Lens1_Lens_0.geometry} material={materials.Lens} />
            <mesh geometry={nodes.Lens2_Lens_0.geometry} material={materials.Lens} />
            <mesh geometry={nodes.Lens_Lens_0.geometry} material={materials.Lens} />
            <mesh geometry={nodes.BackBody001_Logo_0.geometry} material={materials.Logo} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Pixel6.glb')
